# Default configuration file.
# Don't modify this file, instead create `config.yaml` and override what you need.

triggerTag: auto_tagme # Post with this tag will be automatically tagged.
managedTag: auto_tagged # Post managed by auto-tagger will have this tag.
errorTag: auto_tagger_error # If some error occurred post will be tagged with this tag - check log for more details
noMatchTag: tagme # If post can't be found on IQDB it will be tagged with this tag

checkBooruConnectivity: true # If enabled simple check will be performed to ensuere that auto tagger can connect to Szurubooru and Danbooru
storeSourceUrl: true # Controls whether to store Danbooru URL in post source field on Szurubooru.
updateImageRating: true # If true then post rating (safe, questionable, explicit) will be updated from Danbooru.
updateImageNotes: true # If true then post notes will be obtained from Danbooru

singleInstance: # Ensures that only single instance of auto tagger is running.
  enabled: true
  port: 54212   # Port used for locking, make sure that it is not shared with other application.

# Tags mapping configuration.
tags:
  # If true then additional information about tags such as aliases, suggestions or implications will be retrieved from Danbooru.
  obtainAliases: true
  obtainSuggestions: false # Enabling highly unrecomened, will create many unused tags with little gain
  obtainImplications: true
  # Warning: Tags under `ignoreTags` and `remapTags` must be entered as visible on Danbooru. Auto tagger might perform tag name escaping
  # but removing ignored tags and remaping them is peroformed before escaping.
#  ignoreTags:
#    - test # Tag test will be ignored
#    - foo
#  remapTags:
#    - from: bar # Tag 'bar' will be remapped to 'foo'
#      to: foo
#    - from: baz
#      to: foobar
#  remapCategories:
#    # Danbooru has 4 tags categories which can be remapped to any Szurubooru category.
#    # Eg. category `general` will be remapped to 'default'.
#    - from: general
#      to: default
#    - from: artist
#      to: creator
#    - from: character
#      to: hero
#    - from: copyright
#      to: series


szurubooru: # Szurubooru configuration
  apiPath: http://szurubooru.local/api/
  dataPath: http://szurubooru.local/data/
  username: auto-tagger # Auto-tagger should have its own separate account, make sure it has high enough privileges.
  password: auto-tagger
  tagEscaping:
    escapeCharacters: '[]{}/\<>=+;@|!?.''' # All those characters in tags names will be replaced with 'escapeWith' string
    escapeWith: _ # Illegal characters will be replaced by this string
    ignoreFirstColon: true # Colon (':') by default can be used as first character, if true then first colon will not be escpaed
    removeLastDot: true # Some Danbooru tags ends with dot ('.'), if enabled then that dot will be removed

danbooru: # Danbooru configuration
  # Whether to authenticate when sending request to Danbooru, using anonymous mode is not recommend as anonymous
  # user has more restrict API limits.
  anonymous: true
  username: your-username
  apiKey: your-api-key
  # Anonymous users can make 500 requests an hour. Basic members can make 3,000 requests an hour.
  # Gold members can make 10,000 requests an hour. Platinum members can make 20,000 requests an hour.
  hourRequestLimit: 500
